go-app:
  build: .
  ports:
    - "8881:5000"
#  links:
#    - redis
  volumes:
    - ".:/go/src/app"
  command: go run main.go

#redis:
#  restart: always
#  image: redis
#  ports:
#    - "6379:6379"
#  volumes:
#    - ./data/redis/:/data
#  command: redis-server --appendonly yes
